In [5]:
import numpy as np

def gs(X):
    Q, R = np.linalg.qr(X)
    return Q

In [6]:
m = np.array([[1,1,1],[1,1,0], [1,0,0]])
gs(m)

array([[-5.77350269e-01, -4.08248290e-01, -7.07106781e-01],
       [-5.77350269e-01, -4.08248290e-01,  7.07106781e-01],
       [-5.77350269e-01,  8.16496581e-01,  1.11733506e-17]])

In [7]:
v1 = np.array([1, 1,1])
v1/np.linalg.norm(v1)

array([0.57735027, 0.57735027, 0.57735027])

In [8]:
v2 = np.array([-1/3, -1/3,  2/3])
v2/np.linalg.norm(v2)

array([-0.40824829, -0.40824829,  0.81649658])

In [9]:
v3 = np.array([1/2, -1/2, 0])
v3/np.linalg.norm(v3)

array([ 0.70710678, -0.70710678,  0.        ])